name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - name: Login to docker-otomato
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

#       # Build and push image for Dockerfile
    - name: Build and push image for Dockerfile
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        context: ./
        push: true
        tags: otomato/au:latest, otomato/au:${{ github.sha }}
